# Generated by Django 2.1.7 on 2019-03-19 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterDetail',
            fields=[
                ('voter_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Voter ID')),
                ('uidi', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='Aadhar Number ')),
                ('voter_name', models.CharField(max_length=150, verbose_name='Voter Name')),
                ('voted_to', models.CharField(choices=[('bjp', 'Bhartiya Janata Party'), ('aitc', 'All India Trinamool Congress'), ('aap', 'Aam Adami Party'), ('bsp', 'Bahujan Samaj Party'), ('cpi', 'Communist Party Of India'), ('inc', 'Indian National Congress')], max_length=150, verbose_name='Vote To')),
                ('vote_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PollsApp',
            },
        ),
    ]
